language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3.5"
#command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U scikit-learn
  - pip install pandas
script: pytest
